### ISSUE TITLE
Sous deploy crashed

### ISSUE THREAD

**Issue by dkhanaferov** [opentable/sous#495]
[22:02:38][Step 3/3] Running sous deploy -cluster ci-sf -tag 1.0.56 -d -v -flavor na
[22:02:38][Step 3/3] 
[22:02:38][Step 3/3] ################################################################################
[22:02:38][Step 3/3] #                                                                              #
[22:02:38][Step 3/3] #                                       OOPS                                   #
[22:02:38][Step 3/3] #                                                                              #
[22:02:38][Step 3/3] #        Sous has panicked, due to programmer error. Please report this        #
[22:02:38][Step 3/3] #        to the project maintainers at:                                        #
[22:02:38][Step 3/3] #                                                                              #
[22:02:38][Step 3/3] #                https://github.com/opentable/sous/issues                      #
[22:02:38][Step 3/3] #                                                                              #
[22:02:38][Step 3/3] #        Please include this entire message and the stack trace below          #
[22:02:38][Step 3/3] #        and we will investigate and fix it as soon as possible.               #
[22:02:38][Step 3/3] #                                                                              #
[22:02:38][Step 3/3] #        Thanks for your help in improving Sous for all!                       #
[22:02:38][Step 3/3] #                                                                              #
[22:02:38][Step 3/3] #        - The OpenTable DevTools Team                                         #
[22:02:38][Step 3/3] #                                                                              #
[22:02:38][Step 3/3] ################################################################################
[22:02:38][Step 3/3] 
[22:02:38][Step 3/3] Sous Version: 0.5.46+8fe02df2c31c59133834bca6d3386450da6afd62
[22:02:38][Step 3/3] 
[22:02:38][Step 3/3] panic: assignment to entry in nil map
[22:02:38][Step 3/3] 
[22:02:38][Step 3/3] goroutine 1 [running]:
[22:02:38][Step 3/3] panic(0xc05a60, 0xc42026a7c0)
[22:02:38][Step 3/3] /usr/local/go/src/runtime/panic.go:500 +0x1a1
[22:02:38][Step 3/3] github.com/opentable/sous/graph.(*SousGraph).guardedAdd(0xc4202b8dd0, 0xceb349, 0x11, 0xc06ae0, 0xc420010780)
[22:02:38][Step 3/3] /ext-go/1/src/github.com/opentable/sous/graph/actions.go:13 +0xac
[22:02:38][Step 3/3] github.com/opentable/sous/graph.(*SousGraph).GetUpdate(0xc4202b8dd0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x7ffc673737fe, 0x2, 0x7ffc673737e9, ...)
[22:02:38][Step 3/3] /ext-go/1/src/github.com/opentable/sous/graph/actions.go:19 +0x109
[22:02:38][Step 3/3] github.com/opentable/sous/cli.(*SousDeploy).Execute(0xc4202b8dd0, 0xc42000c1d0, 0x0, 0x0, 0xc420014bd0, 0x0)
[22:02:38][Step 3/3] /ext-go/1/src/github.com/opentable/sous/cli/sous_deploy.go:52 +0xae
[22:02:38][Step 3/3] github.com/opentable/sous/util/cmdr.(*CLI).InvokeWithoutPrinting(0xc420255180, 0xc42000c140, 0xa, 0xa, 0xc154a0, 0xc420303ea0)
[22:02:38][Step 3/3] /ext-go/1/src/github.com/opentable/sous/util/cmdr/cli.go:108 +0xa3
[22:02:38][Step 3/3] github.com/opentable/sous/util/cmdr.(*CLI).Invoke(0xc420255180, 0xc42000c140, 0xa, 0xa, 0xa, 0xc4202ed810)
[22:02:38][Step 3/3] /ext-go/1/src/github.com/opentable/sous/util/cmdr/cli.go:76 +0x4d
[22:02:38][Step 3/3] github.com/opentable/sous/cli.(*CLI).Invoke(0xc420253b20, 0xc42000c140, 0xa, 0xa, 0x1336760, 0xc420034010)
[22:02:38][Step 3/3] /ext-go/1/src/github.com/opentable/sous/cli/cli.go:86 +0xc4
[22:02:38][Step 3/3] main.main()
[22:02:38][Step 3/3] /ext-go/1/src/github.com/opentable/sous/main.go:35 +0x215
[22:02:38][Step 3/3] Failed to deploy 1.0.56/na to ci-sf
[22:02:38][Step 3/3] Process exited with code 1
[22:02:38][Step 3/3] Process exited with code 1
[22:02:38][Step 3/3] Step Perform Deployment (Command Line) failed

**Comment by samsalisbury** [comment]
Thanks David, tracked in SOUS-736 <https://opentable.atlassian.net/browse/SOUS-736> I just had to get another release out first, and am now working on this, I’ve found the issue, expect a fix today.

**Comment by samsalisbury** [comment]
Looks like this was already fixed in 0.5.47. Just released 0.5.48 as well. `brew upgrade sous`…

**Comment by samsalisbury** [comment]
@dkhanaferov I believe this is now fixed. Please upgrade to the latest Sous (`brew upgrade sous` on mac, or download from GH releases). Closing for now, feel free to reopen if this crops up again.
